[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/run/supervisord.pid

[unix_http_server]
file=/run/supervisor.sock
chmod=0700
chown=root:root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:eversmartnode]
command=/usr/bin/node /opt/eversmartnode/server.js
directory=/opt/eversmartnode
user=root
autostart=true
autorestart=true
startretries=100
startsecs=2
stopsignal=TERM
stopwaitsecs=10
environment=NODE_PATH="/opt/eversmartnode/node_modules",LD_LIBRARY_PATH="/usr/local/lib:/usr/lib/x86_64-linux-gnu"
stderr_logfile=/var/log/supervisor/eversmartnode.err.log
stdout_logfile=/var/log/supervisor/eversmartnode.out.log
priority=10

[program:hotpocket]
command=/usr/local/bin/hotpocket/hpcore run /contract
user=root
autostart=true
autorestart=true
startretries=100
startsecs=10
stopsignal=TERM
stopwaitsecs=30
environment=NODE_PATH="/opt/eversmartnode/node_modules",LD_LIBRARY_PATH="/usr/local/lib:/usr/lib/x86_64-linux-gnu"
stderr_logfile=/var/log/supervisor/hotpocket.err.log
stdout_logfile=/var/log/supervisor/hotpocket.out.log
priority=20
